#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readLogger_VEGA_BAR54() works", {

  expect_error(
    kwb.logger:::readLogger_VEGA_BAR54(filename = 1)
    # ung?ltiges 'file' Argument
  )
   expect_error(
    kwb.logger:::readLogger_VEGA_BAR54(filename = "a")
    # No such file: a
  )
   expect_error(
    kwb.logger:::readLogger_VEGA_BAR54(filename = c("a", "b"))
    # No such file: ab
  )

})

