#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getProgramBlock() works", {

  expect_error(
    kwb.logger:::.getProgramBlock(txtlines = 1, headerpos = 1)
    # Argument "i" fehlt (ohne Standardwert)
  )

})

