#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getCountryCode() works", {

  expect_error(
    kwb.logger:::.getCountryCode(doc = 1, property = 1)
    # nicht anwendbare Methode f?r 'xpathApply' auf Objekt der Klasse "c('double', 'numeric')" angewendet
  )
   expect_error(
    kwb.logger:::.getCountryCode(doc = 1:2, property = 1)
    # nicht anwendbare Methode f?r 'xpathApply' auf Objekt der Klasse "c('integer', 'numeric')" angewendet
  )
   expect_error(
    kwb.logger:::.getCountryCode(doc = "a", property = 1)
    # nicht anwendbare Methode f?r 'xpathApply' auf Objekt der Klasse "character" angewendet
  )
   expect_error(
    kwb.logger:::.getCountryCode(doc = TRUE, property = 1)
    # nicht anwendbare Methode f?r 'xpathApply' auf Objekt der Klasse "logical" angewendet
  )
   expect_error(
    kwb.logger:::.getCountryCode(doc = as.POSIXct("2018-06-03 23:50:00"), property = 1)
    # nicht anwendbare Methode f?r 'xpathApply' auf Objekt der Klasse "c('POSIXct', 'POSIXt')" angewendet
  )
   expect_error(
    kwb.logger:::.getCountryCode(doc = list(key = c("a", "b"), value = 1:2), property = 1)
    # nicht anwendbare Methode f?r 'xpathApply' auf Objekt der Klasse "list" angewendet
  )

})

