#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getCaptions() works", {

  expect_error(
    kwb.logger:::.getCaptions(txtlines = 1, sep = 1)
    # Argument "colnameDate" fehlt (ohne Standardwert)
  )

})

