#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("reset_locale() works", {

  kwb.logger:::reset_locale(locale_string = "a")
   kwb.logger:::reset_locale(locale_string = c("a", "b"))
   expect_error(
    kwb.logger:::reset_locale(locale_string = 1)
    # nicht-character Argument
  )

})

