#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".splitHeaderLine() works", {

  kwb.logger:::.splitHeaderLine(headerLine = "a", sep = "a")
   kwb.logger:::.splitHeaderLine(headerLine = "a", sep = c("a", "b"))
   expect_error(
    kwb.logger:::.splitHeaderLine(headerLine = 1, sep = 1)
    # ung?ltiges 'text' Argument
  )
   expect_error(
    kwb.logger:::.splitHeaderLine(headerLine = "a", sep = 1)
    # ung?ltiges 'sep' Argument
  )
   expect_error(
    kwb.logger:::.splitHeaderLine(headerLine = c("a", "b"), sep = "a")
    # Zeile 2 hatte keine 2 Elemente
  )

})

