#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".allDataFrameColumnsToNumeric() works", {

  kwb.logger:::.allDataFrameColumnsToNumeric(dframe = "a")
   kwb.logger:::.allDataFrameColumnsToNumeric(dframe = c("a", "b"))
   expect_error(
    kwb.logger:::.allDataFrameColumnsToNumeric(dframe = 1)
    # dim(X) must have a positive length
  )

})

