#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".read_Flaschenbericht.raw() works", {

  expect_error(
    kwb.logger:::.read_Flaschenbericht.raw(samplerFile = 1, headerPattern = 1)
    # 'con' ist keine Verbindung
  )
   expect_error(
    kwb.logger:::.read_Flaschenbericht.raw(samplerFile = "a", headerPattern = 1)
    # kann Verbindung nicht öffnen
  )
   expect_error(
    kwb.logger:::.read_Flaschenbericht.raw(samplerFile = c("a", "b"), headerPattern = 1)
    # ungültiges 'description' Argument
  )

})

