#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".joinDateTimeAndRenameColumns() works", {

  expect_error(
    kwb.logger:::.joinDateTimeAndRenameColumns(x = 1, captions = 1)
    # Indizierung ausserhalb der Grenzen
  )
   expect_error(
    kwb.logger:::.joinDateTimeAndRenameColumns(x = 1, captions = as.POSIXct("2018-06-03 23:50:00"))
    # character string is not in a standard unambiguous format
  )
   expect_error(
    kwb.logger:::.joinDateTimeAndRenameColumns(x = as.POSIXct("2018-06-03 23:50:00"), captions = 1)
    # Argument "colnameDate" fehlt (ohne Standardwert)
  )
   expect_error(
    kwb.logger:::.joinDateTimeAndRenameColumns(x = list(key = c("a", "b"), value = 1:2), captions = 1)
    # Argument "dateformat" fehlt (ohne Standardwert)
  )

})

