#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".delEmptyColumnsToTheRight() works", {

  expect_error(
    kwb.logger:::.delEmptyColumnsToTheRight(bodylines = 1)
    # Argument muss sich in eine nicht-negative ganze Zahl umwandeln lassen
  )

})

