#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getMetadata() works", {

  kwb.logger:::.getMetadata(mylines = 1)
   kwb.logger:::.getMetadata(mylines = 1:2)
   kwb.logger:::.getMetadata(mylines = "a")
   kwb.logger:::.getMetadata(mylines = c("a", "b"))
   kwb.logger:::.getMetadata(mylines = TRUE)
   kwb.logger:::.getMetadata(mylines = FALSE)
   kwb.logger:::.getMetadata(mylines = as.POSIXct("2018-06-03 23:50:00"))
   kwb.logger:::.getMetadata(mylines = list(key = c("a", "b"), value = 1:2))

})

