#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readLogger_PCE_TDS100() works", {

  expect_error(
    kwb.logger:::readLogger_PCE_TDS100(txt = 1)
    # 'con' ist keine Verbindung
  )
   expect_error(
    kwb.logger:::readLogger_PCE_TDS100(txt = "a")
    # kann Verbindung nicht ?ffnen
  )
   expect_error(
    kwb.logger:::readLogger_PCE_TDS100(txt = c("a", "b"))
    # ung?ltiges 'description' Argument
  )

})

