#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getValuesAfterDelimiter() works", {

  expect_error(
    kwb.logger:::.getValuesAfterDelimiter(namevarpairs = 1, sep = 1)
    # nicht-character Argument
  )
   expect_error(
    kwb.logger:::.getValuesAfterDelimiter(namevarpairs = "a", sep = 1)
    # Argument "varname" fehlt (ohne Standardwert)
  )

})

