#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".prepareValuesSection() works", {

  expect_error(
    kwb.logger:::.prepareValuesSection(x = 1, starttime.utc = 1)
    # Argument "hasTempColumn" fehlt (ohne Standardwert)
  )

})

