#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readLogger_InSituInc_Aquatroll() works", {

  expect_error(
    kwb.logger:::readLogger_InSituInc_Aquatroll(csv = 1)
    # ungültiges 'file' Argument
  )
   expect_error(
    kwb.logger:::readLogger_InSituInc_Aquatroll(csv = "a")
    # No such file: a
  )
   expect_error(
    kwb.logger:::readLogger_InSituInc_Aquatroll(csv = c("a", "b"))
    # No such file: ab
  )

})

