#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getLinesWithDate() works", {

  expect_error(
    kwb.logger:::.getLinesWithDate(txtlines = 1, sep = 1)
    # Argument "dateformat" fehlt (ohne Standardwert)
  )

})

