#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getAllEventRows() works", {

  expect_error(
    kwb.logger:::.getAllEventRows(linesWithDate = 1, captions = 1)
    # ung?ltiges 'text' Argument
  )
   expect_error(
    kwb.logger:::.getAllEventRows(linesWithDate = "a", captions = 1)
    # Argument "sep" fehlt (ohne Standardwert)
  )

})

