#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".stopIfInfoTypesAreInvalid() works", {

  kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1, validTypes = 1)
   kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1, validTypes = 1:2)
   kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1, validTypes = TRUE)
   kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1:2, validTypes = 1:2)
   kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = "a", validTypes = "a")
   kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = "a", validTypes = c("a", "b"))
   kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = c("a", "b"), validTypes = c("a", "b"))
   kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = TRUE, validTypes = 1)
   kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = TRUE, validTypes = 1:2)
   kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = TRUE, validTypes = TRUE)
   kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = FALSE, validTypes = FALSE)
   kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = as.POSIXct("2018-06-03 23:50:00"), validTypes = as.POSIXct("2018-06-03 23:50:00"))
   kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = list(key = c("a", "b"), value = 1:2), validTypes = list(key = c("a", "b"), value = 1:2))
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1, validTypes = "a")
    # infotypes (1) must be in c('a')!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1, validTypes = c("a", "b"))
    # infotypes (1) must be in c('a', 'b')!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1, validTypes = FALSE)
    # infotypes (1) must be in c(FALSE)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1, validTypes = as.POSIXct("2018-06-03 23:50:00"))
    # infotypes (1) must be in c(2018-06-03 23:50:00)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1, validTypes = list(key = c("a", "b"), value = 1:2))
    # infotypes (1) must be in c('a', 'b', 1, 2)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1:2, validTypes = 1)
    # infotypes (1, 2) must be in c(1)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1:2, validTypes = "a")
    # infotypes (1, 2) must be in c('a')!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1:2, validTypes = c("a", "b"))
    # infotypes (1, 2) must be in c('a', 'b')!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1:2, validTypes = TRUE)
    # infotypes (1, 2) must be in c(TRUE)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1:2, validTypes = FALSE)
    # infotypes (1, 2) must be in c(FALSE)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1:2, validTypes = as.POSIXct("2018-06-03 23:50:00"))
    # infotypes (1, 2) must be in c(2018-06-03 23:50:00)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = 1:2, validTypes = list(key = c("a", "b"), value = 1:2))
    # infotypes (1, 2) must be in c('a', 'b', 1, 2)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = "a", validTypes = 1)
    # infotypes ('a') must be in c(1)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = "a", validTypes = 1:2)
    # infotypes ('a') must be in c(1, 2)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = "a", validTypes = TRUE)
    # infotypes ('a') must be in c(TRUE)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = "a", validTypes = FALSE)
    # infotypes ('a') must be in c(FALSE)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = "a", validTypes = as.POSIXct("2018-06-03 23:50:00"))
    # infotypes ('a') must be in c(2018-06-03 23:50:00)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = "a", validTypes = list(key = c("a", "b"), value = 1:2))
    # infotypes ('a') must be in c('a', 'b', 1, 2)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = c("a", "b"), validTypes = 1)
    # infotypes ('a', 'b') must be in c(1)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = c("a", "b"), validTypes = 1:2)
    # infotypes ('a', 'b') must be in c(1, 2)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = c("a", "b"), validTypes = "a")
    # infotypes ('a', 'b') must be in c('a')!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = c("a", "b"), validTypes = TRUE)
    # infotypes ('a', 'b') must be in c(TRUE)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = c("a", "b"), validTypes = FALSE)
    # infotypes ('a', 'b') must be in c(FALSE)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = c("a", "b"), validTypes = as.POSIXct("2018-06-03 23:50:00"))
    # infotypes ('a', 'b') must be in c(2018-06-03 23:50:00)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = c("a", "b"), validTypes = list(key = c("a", "b"), value = 1:2))
    # infotypes ('a', 'b') must be in c('a', 'b', 1, 2)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = TRUE, validTypes = "a")
    # infotypes (TRUE) must be in c('a')!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = TRUE, validTypes = c("a", "b"))
    # infotypes (TRUE) must be in c('a', 'b')!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = TRUE, validTypes = FALSE)
    # infotypes (TRUE) must be in c(FALSE)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = TRUE, validTypes = as.POSIXct("2018-06-03 23:50:00"))
    # infotypes (TRUE) must be in c(2018-06-03 23:50:00)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = TRUE, validTypes = list(key = c("a", "b"), value = 1:2))
    # infotypes (TRUE) must be in c('a', 'b', 1, 2)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = FALSE, validTypes = 1)
    # infotypes (FALSE) must be in c(1)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = FALSE, validTypes = 1:2)
    # infotypes (FALSE) must be in c(1, 2)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = FALSE, validTypes = "a")
    # infotypes (FALSE) must be in c('a')!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = FALSE, validTypes = c("a", "b"))
    # infotypes (FALSE) must be in c('a', 'b')!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = FALSE, validTypes = TRUE)
    # infotypes (FALSE) must be in c(TRUE)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = FALSE, validTypes = as.POSIXct("2018-06-03 23:50:00"))
    # infotypes (FALSE) must be in c(2018-06-03 23:50:00)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = FALSE, validTypes = list(key = c("a", "b"), value = 1:2))
    # infotypes (FALSE) must be in c('a', 'b', 1, 2)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = as.POSIXct("2018-06-03 23:50:00"), validTypes = 1)
    # infotypes (2018-06-03 23:50:00) must be in c(1)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = as.POSIXct("2018-06-03 23:50:00"), validTypes = 1:2)
    # infotypes (2018-06-03 23:50:00) must be in c(1, 2)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = as.POSIXct("2018-06-03 23:50:00"), validTypes = "a")
    # infotypes (2018-06-03 23:50:00) must be in c('a')!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = as.POSIXct("2018-06-03 23:50:00"), validTypes = c("a", "b"))
    # infotypes (2018-06-03 23:50:00) must be in c('a', 'b')!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = as.POSIXct("2018-06-03 23:50:00"), validTypes = TRUE)
    # infotypes (2018-06-03 23:50:00) must be in c(TRUE)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = as.POSIXct("2018-06-03 23:50:00"), validTypes = FALSE)
    # infotypes (2018-06-03 23:50:00) must be in c(FALSE)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = as.POSIXct("2018-06-03 23:50:00"), validTypes = list(key = c("a", "b"), value = 1:2))
    # infotypes (2018-06-03 23:50:00) must be in c('a', 'b', 1, 2)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = list(key = c("a", "b"), value = 1:2), validTypes = 1)
    # infotypes ('a', 'b', 1, 2) must be in c(1)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = list(key = c("a", "b"), value = 1:2), validTypes = 1:2)
    # infotypes ('a', 'b', 1, 2) must be in c(1, 2)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = list(key = c("a", "b"), value = 1:2), validTypes = "a")
    # infotypes ('a', 'b', 1, 2) must be in c('a')!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = list(key = c("a", "b"), value = 1:2), validTypes = c("a", "b"))
    # infotypes ('a', 'b', 1, 2) must be in c('a', 'b')!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = list(key = c("a", "b"), value = 1:2), validTypes = TRUE)
    # infotypes ('a', 'b', 1, 2) must be in c(TRUE)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = list(key = c("a", "b"), value = 1:2), validTypes = FALSE)
    # infotypes ('a', 'b', 1, 2) must be in c(FALSE)!
  )
   expect_error(
    kwb.logger:::.stopIfInfoTypesAreInvalid(infotype = list(key = c("a", "b"), value = 1:2), validTypes = as.POSIXct("2018-06-03 23:50:00"))
    # infotypes ('a', 'b', 1, 2) must be in c(2018-06-03 23:50:00)!
  )

})

