#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".timelinesToDataFrame() works", {

  expect_error(
    kwb.logger:::.timelinesToDataFrame(timelines = 1, sep = 1)
    # ung?ltiges 'sep' Argument
  )
   expect_error(
    kwb.logger:::.timelinesToDataFrame(timelines = 1, sep = "a")
    # Argument "dec" fehlt (ohne Standardwert)
  )

})

