#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("read_logger_LT_EDGE_M100_xle() works", {

  expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100_xle(file = 1)
    # ung?ltiges 'file' Argument
  )
   expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100_xle(file = 1:2)
    # XML content does not seem to be XML: '1
# 2'
  )
   expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100_xle(file = "a")
    # XML content does not seem to be XML: 'a'
  )
   expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100_xle(file = c("a", "b"))
    # XML content does not seem to be XML: 'a
# b'
  )
   expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100_xle(file = list(key = c("a", "b"), value = 1:2))
    # XML content does not seem to be XML: 'c("a", "b")
# 1:2'
  )

})

