#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".read_Infospeicher.raw() works", {

  expect_error(
    kwb.logger:::.read_Infospeicher.raw(txt = 1)
    # 'con' ist keine Verbindung
  )
   expect_error(
    kwb.logger:::.read_Infospeicher.raw(txt = "a")
    # kann Verbindung nicht öffnen
  )
   expect_error(
    kwb.logger:::.read_Infospeicher.raw(txt = c("a", "b"))
    # ungültiges 'description' Argument
  )

})

