#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readLogger_FLEXIM_F601() works", {

  expect_error(
    kwb.logger:::readLogger_FLEXIM_F601(filename = 1)
    # ung?ltiges 'description' Argument
  )
   expect_error(
    kwb.logger:::readLogger_FLEXIM_F601(filename = "a")
    # kann Verbindung nicht ?ffnen
  )

})

