#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getMeta_SIGMA_SD900() works", {

  expect_error(
    kwb.logger:::.getMeta_SIGMA_SD900(filepath = 1, headerPattern = 1)
    # 'con' ist keine Verbindung
  )
   expect_error(
    kwb.logger:::.getMeta_SIGMA_SD900(filepath = "a", headerPattern = 1)
    # kann Verbindung nicht ?ffnen
  )
   expect_error(
    kwb.logger:::.getMeta_SIGMA_SD900(filepath = c("a", "b"), headerPattern = 1)
    # ung?ltiges 'description' Argument
  )

})

