#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".splitValueAndUnit() works", {

  expect_error(
    kwb.logger:::.splitValueAndUnit(valueAndUnit = 1)
    # nicht-character Argument
  )
   expect_error(
    kwb.logger:::.splitValueAndUnit(valueAndUnit = "a")
    # Indizierung ausserhalb der Grenzen
  )

})

