#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("read_logger_LT_EDGE_M100_csv() works", {

  expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100_csv(file = 1)
    # ung?ltiges 'file' Argument
  )
   expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100_csv(file = "a")
    # No such file: a
  )
   expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100_csv(file = c("a", "b"))
    # No such file: ab
  )

})

