#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getValidTimes() works", {

  expect_error(
    kwb.logger:::.getValidTimes(mylines = 1)
    # is.character(x) is not TRUE
  )
   expect_error(
    kwb.logger:::.getValidTimes(mylines = "a")
    # ung?ltiges 'times' Argument
  )

})

