#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".to_timestamp_columns() works", {

  kwb.logger:::.to_timestamp_columns(TimestampInFile = "a")
   kwb.logger:::.to_timestamp_columns(TimestampInFile = c("a", "b"))
   expect_error(
    kwb.logger:::.to_timestamp_columns(TimestampInFile = 1)
    # is.character(timestamp) is not TRUE
  )

})

