#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".allButFirstToLower() works", {

  kwb.logger:::.allButFirstToLower(x = 1)
   kwb.logger:::.allButFirstToLower(x = "a")
   kwb.logger:::.allButFirstToLower(x = TRUE)
   kwb.logger:::.allButFirstToLower(x = FALSE)
   kwb.logger:::.allButFirstToLower(x = as.POSIXct("2018-06-03 23:50:00"))
   expect_error(
    kwb.logger:::.allButFirstToLower(x = 1:2)
    # length(x) == 1 is not TRUE
  )

})

