#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readLogger_Buehler_4010_Flaschenbericht() works", {

  expect_error(
    kwb.logger:::readLogger_Buehler_4010_Flaschenbericht(samplerFile = 1)
    # 'con' ist keine Verbindung
  )
   expect_error(
    kwb.logger:::readLogger_Buehler_4010_Flaschenbericht(samplerFile = "a")
    # kann Verbindung nicht öffnen
  )
   expect_error(
    kwb.logger:::readLogger_Buehler_4010_Flaschenbericht(samplerFile = c("a", "b"))
    # ungültiges 'description' Argument
  )

})

