#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readLogger_Buehler_4010_Infospeicher() works", {

  expect_error(
    kwb.logger:::readLogger_Buehler_4010_Infospeicher(samplerFile = 1, ... = 1)
    # unbenutztes Argument (... = 1)
  )
   expect_error(
    kwb.logger:::readLogger_Buehler_4010_Infospeicher(samplerFile = 1, ... = 1:2)
    # unbenutztes Argument (... = 1:2)
  )
   expect_error(
    kwb.logger:::readLogger_Buehler_4010_Infospeicher(samplerFile = 1, ... = "a")
    # unbenutztes Argument (... = "a")
  )
   expect_error(
    kwb.logger:::readLogger_Buehler_4010_Infospeicher(samplerFile = 1, ... = c("a", "b"))
    # unbenutztes Argument (... = c("a", "b"))
  )
   expect_error(
    kwb.logger:::readLogger_Buehler_4010_Infospeicher(samplerFile = 1, ... = TRUE)
    # unbenutztes Argument (... = TRUE)
  )
   expect_error(
    kwb.logger:::readLogger_Buehler_4010_Infospeicher(samplerFile = 1, ... = FALSE)
    # unbenutztes Argument (... = FALSE)
  )
   expect_error(
    kwb.logger:::readLogger_Buehler_4010_Infospeicher(samplerFile = 1, ... = as.POSIXct("2018-06-03 23:50:00"))
    # unbenutztes Argument (... = 1528062600)
  )
   expect_error(
    kwb.logger:::readLogger_Buehler_4010_Infospeicher(samplerFile = 1, ... = list(key = c("a", "b"), value = 1:2))
    # unbenutztes Argument (... = list(key = c("a", "b"), value = 1:2))
  )

})

