#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".collapse() works", {

  kwb.logger:::.collapse(x = 1)
   kwb.logger:::.collapse(x = 1:2)
   kwb.logger:::.collapse(x = "a")
   kwb.logger:::.collapse(x = c("a", "b"))
   kwb.logger:::.collapse(x = TRUE)
   kwb.logger:::.collapse(x = FALSE)
   kwb.logger:::.collapse(x = as.POSIXct("2018-06-03 23:50:00"))
   kwb.logger:::.collapse(x = list(key = c("a", "b"), value = 1:2))

})

