#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("read_logger_LT_EDGE_M100() works", {

  expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100(file = 1, ... = 1)
    # file with extension '.csv' or '.xle' expected (filename is '1'
  )
   expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100(file = 1:2, ... = 1)
    # file with extension '.csv' or '.xle' expected (filename is '12'
  )
   expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100(file = "a", ... = 1)
    # file with extension '.csv' or '.xle' expected (filename is 'a'
  )
   expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100(file = c("a", "b"), ... = 1)
    # file with extension '.csv' or '.xle' expected (filename is 'ab'
  )
   expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100(file = TRUE, ... = 1)
    # file with extension '.csv' or '.xle' expected (filename is 'TRUE'
  )
   expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100(file = FALSE, ... = 1)
    # file with extension '.csv' or '.xle' expected (filename is 'FALSE'
  )
   expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100(file = as.POSIXct("2018-06-03 23:50:00"), ... = 1)
    # file with extension '.csv' or '.xle' expected (filename is '2018-06-03 23:50:00'
  )
   expect_error(
    kwb.logger:::read_logger_LT_EDGE_M100(file = list(key = c("a", "b"), value = 1:2), ... = 1)
    # file with extension '.csv' or '.xle' expected (filename is 'c("a", "b")1:2'
  )

})

