#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readLogger_PCE_PA8000() works", {

  expect_error(
    kwb.logger:::readLogger_PCE_PA8000(filename = 1)
    # ung?ltiges 'file' Argument
  )
   expect_error(
    kwb.logger:::readLogger_PCE_PA8000(filename = "a")
    # No such file: a
  )
   expect_error(
    kwb.logger:::readLogger_PCE_PA8000(filename = c("a", "b"))
    # No such file: ab
  )

})

