#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".addRowNumberLeft() works", {

  kwb.logger:::.addRowNumberLeft(txtlines = 1, sep = "a")
   kwb.logger:::.addRowNumberLeft(txtlines = 1, sep = c("a", "b"))
   kwb.logger:::.addRowNumberLeft(txtlines = 1:2, sep = "a")
   kwb.logger:::.addRowNumberLeft(txtlines = 1:2, sep = c("a", "b"))
   kwb.logger:::.addRowNumberLeft(txtlines = "a", sep = "a")
   kwb.logger:::.addRowNumberLeft(txtlines = "a", sep = c("a", "b"))
   kwb.logger:::.addRowNumberLeft(txtlines = c("a", "b"), sep = "a")
   kwb.logger:::.addRowNumberLeft(txtlines = c("a", "b"), sep = c("a", "b"))
   kwb.logger:::.addRowNumberLeft(txtlines = TRUE, sep = "a")
   kwb.logger:::.addRowNumberLeft(txtlines = TRUE, sep = c("a", "b"))
   kwb.logger:::.addRowNumberLeft(txtlines = FALSE, sep = "a")
   kwb.logger:::.addRowNumberLeft(txtlines = FALSE, sep = c("a", "b"))
   kwb.logger:::.addRowNumberLeft(txtlines = as.POSIXct("2018-06-03 23:50:00"), sep = "a")
   kwb.logger:::.addRowNumberLeft(txtlines = as.POSIXct("2018-06-03 23:50:00"), sep = c("a", "b"))
   kwb.logger:::.addRowNumberLeft(txtlines = list(key = c("a", "b"), value = 1:2), sep = "a")
   kwb.logger:::.addRowNumberLeft(txtlines = list(key = c("a", "b"), value = 1:2), sep = c("a", "b"))
   expect_error(
    kwb.logger:::.addRowNumberLeft(txtlines = 1, sep = 1)
    # ung?ltiger Separator
  )

})

