#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".groupLinesByEventType() works", {

  expect_error(
    kwb.logger:::.groupLinesByEventType(linesWithDate = 1, captions = 1)
    # Argument "sep" fehlt (ohne Standardwert)
  )

})

