#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".splitSection() works", {

  expect_error(
    kwb.logger:::.splitSection(x = 1)
    # nicht-character Argument
  )
   expect_error(
    kwb.logger:::.splitSection(x = "a")
    # no lines available in input
  )

})

