#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readLogger_Ori_MLog() works", {

  expect_error(
    kwb.logger:::readLogger_Ori_MLog(csv = 1, ... = 1)
    # ung?ltiges 'file' Argument
  )
   expect_error(
    kwb.logger:::readLogger_Ori_MLog(csv = "a", ... = 1)
    # No such file: a
  )
   expect_error(
    kwb.logger:::readLogger_Ori_MLog(csv = c("a", "b"), ... = 1)
    # No such file: ab
  )

})

