#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readLogger_Ori_BasicEx1() works", {

  expect_error(
    kwb.logger:::readLogger_Ori_BasicEx1(filepath = 1)
    # 'con' ist keine Verbindung
  )
   expect_error(
    kwb.logger:::readLogger_Ori_BasicEx1(filepath = "a")
    # kann Verbindung nicht ?ffnen
  )
   expect_error(
    kwb.logger:::readLogger_Ori_BasicEx1(filepath = c("a", "b"))
    # ung?ltiges 'description' Argument
  )

})

