#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getStartTimeFromBasicsSection() works", {

  kwb.logger:::.getStartTimeFromBasicsSection(x = list(key = c("a", "b"), value = 1:2))
   expect_error(
    kwb.logger:::.getStartTimeFromBasicsSection(x = 1)
    # $ operator is invalid for atomic vectors
  )

})

