#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("read_aquatroll_data() works", {

  expect_error(
    kwb.logger:::read_aquatroll_data(file = 1)
    # 'file' must be a character string or connection
  )
   expect_error(
    kwb.logger:::read_aquatroll_data(file = "a")
    # kann Verbindung nicht öffnen
  )
   expect_error(
    kwb.logger:::read_aquatroll_data(file = c("a", "b"))
    # ungültiges 'description' Argument
  )

})

