#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readLogger_NIVUS_PCM4() works", {

  expect_error(
    kwb.logger:::readLogger_NIVUS_PCM4(csv = 1)
    # 'file' must be a character string or connection
  )
   expect_error(
    kwb.logger:::readLogger_NIVUS_PCM4(csv = "a")
    # kann Verbindung nicht ?ffnen
  )
   expect_error(
    kwb.logger:::readLogger_NIVUS_PCM4(csv = c("a", "b"))
    # ung?ltiges 'description' Argument
  )

})

