#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".indicesOfContext() works", {

  kwb.logger:::.indicesOfContext(indices = 1)
   kwb.logger:::.indicesOfContext(indices = 1:2)
   kwb.logger:::.indicesOfContext(indices = TRUE)
   kwb.logger:::.indicesOfContext(indices = FALSE)
   kwb.logger:::.indicesOfContext(indices = as.POSIXct("2018-06-03 23:50:00"))
   expect_error(
    kwb.logger:::.indicesOfContext(indices = "a")
    # nicht-numerisches Argument f?r bin?ren Operator
  )

})

